In [1]:
import pandas as pd

In [ ]:
"D:\freelance\portifolo\data analyst\client\faccebook pages\facebook_page\back up facebook\copies 2\250f_sydney.csv"

In [167]:
df=pd.read_csv(r"D:\freelance\portifolo\data analyst\client\faccebook pages\facebook_page\back up facebook\copies 2\duplicated_r.csv")

In [174]:
df

,Facebook_url,LGA_region,Page_Name,Page_Created_date,Address,Phone_number,Email,Website_url
0,https://www.facebook.com/CanadaAustraliaMigration,Sydney,Innovative Business Resources,2018-06-19,"4/9 Thiruvalluvar 1st Street, K K Nagar (West)...",044 4865 1212,NaN,http://www.theibr.com/
1,https://www.facebook.com/profile.php?id=100090...,Sydney,Sydney Nash,2023-02-11,NaN,NaN,NaN,NaN
2,https://www.facebook.com/Mattrimony,Sydney,Mattrimony,2011-12-18,"North Manly, Sydney, NSW, Australia, 2100",+61 466 777 080,info@mattrimony.com.au,http://www.mattrimony.com.au/
3,https://www.facebook.com/choicebusinesscollege,Sydney,Choice Business College - RTO 41297,2015-12-07,NaN,+61 2 9630 6999,info@cbc.edu.au,http://cbc.edu.au/
4,https://www.facebook.com/DesignCrowd,Sydney,DesignCrowd,2010-07-22,"Level 4, 2 HIll Street,, Darlinghurst, NSW, Au...",NaN,support@designcrowd.com,http://www.designcrowd.com/
...,...,...,...,...,...,...,...,...
891,https://www.facebook.com/fatimahennadesign,Sydney,Henna tattoo,2014-12-01,"Bankstown, NSW, Australia, 3072",+61 420 902 020,NaN,NaN
892,https://www.facebook.com/floodrestorationsydney,Sydney,Flood Restoration Sydney,2017-12-30,"6/100 Belmont st , Alexandria, NSW, Australia,...",+61 1300 660 276,NaN,http://www.floodrestoration.sydney/
893,https://www.facebook.com/dataresilienceAU,Sydney,Dataresilience,2019-07-29,"Sydney, NSW, Australia, 2000",+61 2 9098 9099,info@dataresilience.com.au,https://www.dataresilience.com.au/
894,https://www.facebook.com/rlaurenceplumbing,Sydney,R. Laurence Plumbing,2019-03-13,NaN,+61 1300 508 806,info@rlaurenceplumbing.com.au,http://www.rlaurenceplumbing.com.au/
895,https://www.facebook.com/ilscsydney,Sydney,ILSC-Sydney,2013-11-27,"Level 6 & 7, 540 George Street, Sydney, NSW, A...",+61 2 9247 1744,NaN,https://www.ilsc.com/language-schools/destinat...

In [169]:


# Filter out rows with missing years
missing_years = df['Page_Created_date'].str.extract(r'^(\d{2}\-\w+)$')[0]

# Add '2023' to the missing years dates
df.loc[missing_years.notnull(), 'Page_Created_date'] = missing_years + '-2023'

# Convert 'Page_Created_date' column to datetime type
df['Page_Created_date'] = pd.to_datetime(df['Page_Created_date'], errors='coerce').dt.strftime('%d-%b-%Y')

# Print the DataFrame with updated dates
print(df)

                                          Facebook_url LGA_region  \
0    https://www.facebook.com/CanadaAustraliaMigration     Sydney
1    https://www.facebook.com/profile.php?id=100090...     Sydney
2                  https://www.facebook.com/Mattrimony     Sydney
3       https://www.facebook.com/choicebusinesscollege     Sydney
4                 https://www.facebook.com/DesignCrowd     Sydney
..                                                 ...        ...
891         https://www.facebook.com/fatimahennadesign     Sydney
892    https://www.facebook.com/floodrestorationsydney     Sydney
893          https://www.facebook.com/dataresilienceAU     Sydney
894         https://www.facebook.com/rlaurenceplumbing     Sydney
895                https://www.facebook.com/ilscsydney     Sydney

                               Page_Name Page_Created_date  \
0          Innovative Business Resources       19-Jun-2018
1                            Sydney Nash       11-Feb-2023
2                             Mattrimony       18-Dec-2011
3    Choice Business College - RTO 41297       07-Dec-2015
4                            DesignCrowd       22-Jul-2010
..                                   ...               ...
891                         Henna tattoo       01-Dec-2014
892             Flood Restoration Sydney       30-Dec-2017
893                       Dataresilience       29-Jul-2019
894                 R. Laurence Plumbing       13-Mar-2019
895                          ILSC-Sydney       27-Nov-2013

                                               Address      Phone_number  \
0    4/9 Thiruvalluvar 1st Street, K K Nagar (West)...     044 4865 1212
1                                                  NaN               NaN
2            North Manly, Sydney, NSW, Australia, 2100   +61 466 777 080
3                                                  NaN   +61 2 9630 6999
4    Level 4, 2 HIll Street,, Darlinghurst, NSW, Au...               NaN
..                                                 ...               ...
891                    Bankstown, NSW, Australia, 3072   +61 420 902 020
892  6/100 Belmont st , Alexandria, NSW, Australia,...  +61 1300 660 276
893                       Sydney, NSW, Australia, 2000   +61 2 9098 9099
894                                                NaN  +61 1300 508 806
895  Level 6 & 7, 540 George Street, Sydney, NSW, A...   +61 2 9247 1744

                             Email  \
0                              NaN
1                              NaN
2           info@mattrimony.com.au
3                  info@cbc.edu.au
4          support@designcrowd.com
..                             ...
891                            NaN
892                            NaN
893     info@dataresilience.com.au
894  info@rlaurenceplumbing.com.au
895                            NaN

                                           Website_url
0                               http://www.theibr.com/
1                                                  NaN
2                        http://www.mattrimony.com.au/
3                                   http://cbc.edu.au/
4                          http://www.designcrowd.com/
..                                                 ...
891                                                NaN
892                http://www.floodrestoration.sydney/
893                 https://www.dataresilience.com.au/
894               http://www.rlaurenceplumbing.com.au/
895  https://www.ilsc.com/language-schools/destinat...

[896 rows x 8 columns]

In [172]:
# Convert 'Page_Created_date' column to datetime type
df['Page_Created_date'] = pd.to_datetime(df['Page_Created_date'], errors='coerce')

# Filter DataFrame for the year 2023
filtered_df = df[df['Page_Created_date'].dt.year == 2023]

# Save filtered DataFrame to a CSV file
filtered_df.to_csv('filtered_data_2023.csv', index=False)

In [173]:
# Filter DataFrame for April 2023
filtered_df = df[(df['Page_Created_date'].dt.year == 2023) & (df['Page_Created_date'].dt.month == 4)]

# Save filtered DataFrame to a CSV file
filtered_df.to_csv('filtered_data_sydney_april_2023.csv', index=False)